In [1]:
import numpy as np
b = []
for i in range(8):
    c = []
    for j in range(i%2,8 + i%2):
        c.append(j % 2)
    b.append(c)

a = np.array(b)
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [15]:
a = np.arange(0,4,4/25).reshape(5,5)
print(a)

[[0.   0.16 0.32 0.48 0.64]
 [0.8  0.96 1.12 1.28 1.44]
 [1.6  1.76 1.92 2.08 2.24]
 [2.4  2.56 2.72 2.88 3.04]
 [3.2  3.36 3.52 3.68 3.84]]


In [16]:
a = np.random.random((3,3,3))
print(a)

[[[0.80539383 0.2937062  0.84065141]
  [0.23643631 0.70742975 0.3217413 ]
  [0.90723895 0.85115875 0.44118708]]

 [[0.61369371 0.0134721  0.34182382]
  [0.64441191 0.21791835 0.77215679]
  [0.48647409 0.32758779 0.55512948]]

 [[0.96196111 0.11238108 0.630748  ]
  [0.73490713 0.82022953 0.20400899]
  [0.55425748 0.88388447 0.88266112]]]


In [17]:
b = []
n = 8
for i in range(n):
    c = []
    for j in range(n):
        if i == n - 1 or i == 0 or j == n - 1 or j == 0:
            c.append(1)
        else:
            c.append(0)
    b.append(c)

a = np.array(b)
print(a)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [23]:
a = np.random.random(20)
a.sort()

print(a)

[0.0305987  0.08720485 0.09155349 0.15511737 0.20546116 0.23612394
 0.28138584 0.34154359 0.3580033  0.39586186 0.51917235 0.54587751
 0.63534012 0.65368511 0.6635694  0.7364107  0.8206806  0.92097057
 0.97154795 0.98679284]


In [2]:
import numpy as np
a = np.arange(0,4,4/20).reshape(4,5)
print(a.shape) # shape
print(a.size) #
print(a.ndim)

(4, 5)
20
2


In [21]:
import pandas as pd
a = pd.Series([1,2,2])
b = pd.Series([3,4,5])
distance = 0
for i in range(a.size):
    distance += (a[i] - b[i])**2
print(distance**0.5)

4.123105625617661


In [8]:
import pandas as pd
dataframe = pd.read_csv("baby_names_2000.csv")
dataframe.head(2)

year    name gender  count
0  2000   Emily      F  25956
1  2000  Hannah      F  23082

In [7]:
dataframe.tail(3)

year   name gender  count
624233  2018  Zyrie      M      5
624234  2018  Zyron      M      5
624235  2018  Zzyzx      M      5

In [10]:
dataframe.shape

(624236, 4)

In [11]:
dataframe.describe()

year          count
count  624236.000000  624236.000000
mean     2009.115961     113.971929
std         5.383550     754.696900
min      2000.000000       5.000000
25%      2005.000000       7.000000
50%      2009.000000      11.000000
75%      2014.000000      29.000000
max      2018.000000   34477.000000

In [12]:
dataframe.iloc[1:4]

year     name gender  count
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997

In [14]:
dataframe[dataframe['name'] == 'Madison'].head(5)

year     name gender  count
2      2000  Madison      F  19968
18699  2000  Madison      M    138
29773  2001  Madison      F  22164
48865  2001  Madison      M    126
60047  2002  Madison      F  21773

In [20]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
# dataframe.head(2)
scaler = MinMaxScaler()
dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
scaler = StandardScaler()
dataframe[['sepal_width_cm']] = scaler.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]